parameters:
    pim_custom_entity.updater.custom_entity.class: Pim\Bundle\CustomEntityBundle\Updater\Updater

services:
    pim_custom_entity.saver.custom_entity:
        class: '%pim_catalog.saver.base.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
            - '%pim_reference_data.model.reference_data.interface%'

    pim_custom_entity.remover.custom_entity:
        class: '%pim_catalog.remover.base.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
            - '%pim_reference_data.model.reference_data.interface%'

    pim_custom_entity.updater.custom_entity:
        class: '%pim_custom_entity.updater.custom_entity.class%'
        arguments:
            - '@property_accessor'
            - '@pim_catalog.repository.locale'
            - '@doctrine.orm.entity_manager'
            - '@akeneo_file_storage.file_storage.file.file_storer'
            - '%tmp_storage_dir%'
