parameters:
    pim_custom_entity.normalizer.flat.reference_data.class: Pim\Bundle\CustomEntityBundle\Normalizer\Flat\ReferenceDataNormalizer
    pim_custom_entity.normalizer.flat.translation.class: Pim\Bundle\CustomEntityBundle\Normalizer\Flat\TranslationNormalizer

    pim_custom_entity.normalizer.custom_entity.class: Pim\Bundle\CustomEntityBundle\Normalizer\CustomEntityNormalizer
    pim_custom_entity.normalizer.standard.minimal.class: Pim\Bundle\CustomEntityBundle\Normalizer\Standard\MinimalStandardNormalizer

services:
    pim_custom_entity.normalizer.internal_api.custom_entity:
        class: '%pim_custom_entity.normalizer.custom_entity.class%'
        arguments:
            - '@pim_serializer'
            - '@pim_versioning.manager.version'
            - '@pim_enrich.normalizer.version'
            - '@pim_custom_entity.provider.structure_version.custom_entity'

    pim_custom_entity.normalizer.standard.minimal:
        public: false
        class: '%pim_custom_entity.normalizer.standard.minimal.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 150 }

    pim_custom_entity.normalizer.flat.reference_data:
        public: false
        class: '%pim_custom_entity.normalizer.flat.reference_data.class%'
        arguments:
            - '@pim_custom_entity.metadata.target_entity_resolver'
            - '@pim_custom_entity.metadata.class_metadata_registry'
            - '@property_accessor'
            - '@pim_custom_entity.normalizer.flat.translation'
        calls:
            - ['setSkippedFields', [ ['id', 'created', 'updated', 'locale'] ] ]

    pim_custom_entity.normalizer.flat.translation:
        public: false
        class: '%pim_custom_entity.normalizer.flat.translation.class%'
        arguments:
            - '@pim_custom_entity.metadata.class_metadata_registry'
            - '@property_accessor'
        calls:
            - ['setSkippedFields', [ ['id', 'locale', 'foreignKey'] ] ]
