parameters:
    pim_custom_entity.configuration.registry.class: Pim\Bundle\CustomEntityBundle\Configuration\Registry
    pim_custom_entity.configuration.default.class:  Pim\Bundle\CustomEntityBundle\Configuration\Configuration
    pim_custom_entity.controller.class:             Pim\Bundle\CustomEntityBundle\Controller\Controller
    pim_custom_entity.manager.class:                Pim\Bundle\CustomEntityBundle\Manager\Manager
    pim_custom_entity.manager.registry.class:       Pim\Bundle\CustomEntityBundle\Manager\Registry
    pim_custom_entity.action_event_manager.class:   Pim\Bundle\CustomEntityBundle\Event\ActionEventManager
    pim_custom_entity.repository.attribute.class:   Pim\Bundle\CustomEntityBundle\Entity\Repository\AttributeRepository
    pim_catalog.resolver.fqcn.class:                Pim\Bundle\CustomEntityBundle\Resolver\FQCNResolver

services:
    pim_custom_entity.configuration.registry:
        class: '%pim_custom_entity.configuration.registry.class%'
        arguments:
            - '@service_container'

    pim_custom_entity.action_event_manager:
        class: '%pim_custom_entity.action_event_manager.class%'
        arguments:
            - '@event_dispatcher'

    pim_custom_entity.factory.custom_entity:
        class: Pim\Bundle\CustomEntityBundle\Entity\CustomEntityFactory
        arguments:
            - '@pim_custom_entity.configuration.registry'

    pim_custom_entity.repository.attribute:
        class: '%pim_custom_entity.repository.attribute.class%'
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '%pim_catalog.entity.attribute.class%'

    pim_custom_entity.provider.structure_version.custom_entity:
        class: '%pim_enrich.provider.structure_version.class%'
        arguments:
            - '@pim_versioning.repository.version'
